live_config_reload = true

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.95
blur = true

[window.padding]
x = 5
y = 5
